sudo: required
services:
  - docker

before_install:
  - docker build -t alexaleluia12/rapp-kb -f Dockerfile.dev .

script:
  - docker run alexaleluia12/rapp-kb npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-606790527234"
  bucket_path: "docker-react"
  on:
    branch: master
  skip_cleanup: true
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
